# Generated by Django 5.2.7 on 2025-11-05 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('excerpt', models.TextField(blank=True)),
                ('source', models.CharField(default='facebook', max_length=50)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_fetched', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmark')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'unique_together': {('bookmark', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(related_name='bookmarks', through='bookmarks.BookmarkTag', to='tags.tag'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=2000)),
                ('media_type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('other', 'other')], default='image', max_length=20)),
                ('thumbnail_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='bookmarks.bookmark')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='bookmarks_b_user_id_f7315e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'url_hash')},
        ),
    ]
