services:
  - type: web
    name: fbnotes
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn fbnotes.wsgi --bind 0.0.0.0:$PORT"
